# Generated by Django 5.1.1 on 2024-09-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date_Created',
            new_name='Date_posted',
        ),
    ]
